Count,Message,Traceback,Nodes
10,'NoneType' object has no attribute 'url',"  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 490, in execute_task
    task(self.user)
  File ""/home/erods-chouette/PycharmProjects/synchronizeExperimentation/workload_generators/locust/teastore_locustfile-custom-scale.py"", line 56, in load
    self.browse()
  File ""/home/erods-chouette/PycharmProjects/synchronizeExperimentation/workload_generators/locust/teastore_locustfile-custom-scale.py"", line 112, in browse
    product_request = self.client.get(""/product"", params={""id"": product_id})
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 252, in get
    return self.request(""GET"", url, data=data, json=json, **kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 196, in request
    url = request_before_redirect.url  # type: ignore
",local
15,'NoneType' object has no attribute 'url',"  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 490, in execute_task
    task(self.user)
  File ""/home/erods-chouette/PycharmProjects/synchronizeExperimentation/workload_generators/locust/teastore_locustfile-custom-scale.py"", line 56, in load
    self.browse()
  File ""/home/erods-chouette/PycharmProjects/synchronizeExperimentation/workload_generators/locust/teastore_locustfile-custom-scale.py"", line 107, in browse
    category_request = self.client.get(""/category"", params={""page"": page, ""category"": category_id})
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 252, in get
    return self.request(""GET"", url, data=data, json=json, **kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 196, in request
    url = request_before_redirect.url  # type: ignore
",local
1,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 490, in execute_task
    task(self.user)
  File ""/home/erods-chouette/PycharmProjects/synchronizeExperimentation/workload_generators/locust/teastore_locustfile-custom-scale.py"", line 56, in load
    self.browse()
  File ""/home/erods-chouette/PycharmProjects/synchronizeExperimentation/workload_generators/locust/teastore_locustfile-custom-scale.py"", line 116, in browse
    if cart_request.ok:
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/models.py"", line 764, in ok
    self.raise_for_status()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 61, in raise_for_status
    raise self.error
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 371, in __exit__
    self.raise_for_status()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 61, in raise_for_status
    raise self.error
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 237, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/sessions.py"", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/sessions.py"", line 703, in send
    r = adapter.send(request, **kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/adapters.py"", line 682, in send
    raise ConnectionError(err, request=request)
",local
1,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 490, in execute_task
    task(self.user)
  File ""/home/erods-chouette/PycharmProjects/synchronizeExperimentation/workload_generators/locust/teastore_locustfile-custom-scale.py"", line 56, in load
    self.browse()
  File ""/home/erods-chouette/PycharmProjects/synchronizeExperimentation/workload_generators/locust/teastore_locustfile-custom-scale.py"", line 113, in browse
    if product_request.ok:
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/models.py"", line 764, in ok
    self.raise_for_status()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 61, in raise_for_status
    raise self.error
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 371, in __exit__
    self.raise_for_status()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 61, in raise_for_status
    raise self.error
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 237, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/sessions.py"", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/sessions.py"", line 703, in send
    r = adapter.send(request, **kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/adapters.py"", line 682, in send
    raise ConnectionError(err, request=request)
",local
1,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))","  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 490, in execute_task
    task(self.user)
  File ""/home/erods-chouette/PycharmProjects/synchronizeExperimentation/workload_generators/locust/teastore_locustfile-custom-scale.py"", line 55, in load
    self.login()
  File ""/home/erods-chouette/PycharmProjects/synchronizeExperimentation/workload_generators/locust/teastore_locustfile-custom-scale.py"", line 91, in login
    if login_request.ok:
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/models.py"", line 764, in ok
    self.raise_for_status()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 61, in raise_for_status
    raise self.error
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 371, in __exit__
    self.raise_for_status()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 61, in raise_for_status
    raise self.error
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 237, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/sessions.py"", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/sessions.py"", line 703, in send
    r = adapter.send(request, **kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/adapters.py"", line 682, in send
    raise ConnectionError(err, request=request)
",local
1,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))","  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/user/task.py"", line 490, in execute_task
    task(self.user)
  File ""/home/erods-chouette/PycharmProjects/synchronizeExperimentation/workload_generators/locust/teastore_locustfile-custom-scale.py"", line 56, in load
    self.browse()
  File ""/home/erods-chouette/PycharmProjects/synchronizeExperimentation/workload_generators/locust/teastore_locustfile-custom-scale.py"", line 108, in browse
    if category_request.ok:
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/models.py"", line 764, in ok
    self.raise_for_status()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 61, in raise_for_status
    raise self.error
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 371, in __exit__
    self.raise_for_status()
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 61, in raise_for_status
    raise self.error
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/locust/clients.py"", line 237, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/sessions.py"", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/sessions.py"", line 703, in send
    r = adapter.send(request, **kwargs)
  File ""/home/erods-chouette/.local/lib/python3.10/site-packages/requests/adapters.py"", line 682, in send
    raise ConnectionError(err, request=request)
",local
